# Generated by Django 5.2.1 on 2025-05-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivogenerado',
            name='documento_generado',
            field=models.FileField(upload_to='output'),
        ),
    ]
